# -*- coding: utf-8 -*-
ROLES=[
dict(slug='muhasebeci-cv-ornegi',short='Muhasebeci CV Örneği',desc='Muhasebe elemanı ve uzmanı için örnek CV ve rehber',
 title="Muhasebeci CV Örneği: Muhasebe Elemanı ve Uzmanı CV'si Nasıl Hazırlanır?",
 mdesc="Muhasebeci CV örneği ve rehberi: muhasebe elemanı, muhasebe uzmanı ve mali müşavir adayları için ATS uyumlu CV yazımı, beceriler ve sık yapılan hatalar.",
 kw='muhasebeci cv örneği, muhasebe elemanı cv, muhasebe uzmanı cv nasıl hazırlanır, muhasebe cv örnekleri, mali müşavir cv, ön muhasebe cv',
 h1='Muhasebeci CV Örneği: Nasıl Hazırlanır?',
 lede="Muhasebe ilanlarında işverenler önce hangi programları kullandığınıza, hangi süreçleri yönettiğinize ve hata payınızın ne kadar düşük olduğuna bakar. Muhasebe elemanı CV'nizi bu üç soruya hızlı cevap verecek şekilde kurun.",
 must=["Kullandığınız muhasebe ve ERP programları (Logo, Mikro, Luca, Zirve, SAP gibi)","Bilanço, mizan, KDV ve muhtasar beyanname hazırlama deneyimi","e-Fatura, e-Defter ve e-Arşiv süreçlerine hâkimiyet","Cari hesap takibi, banka ve firma mutabakatı","Stajyerlik, SMMM veya YMM sürecindeyseniz durumunuz"],
 sample="4 yıllık deneyime sahip muhasebe uzmanı. Aylık kapanış, KDV beyannamesi ve mutabakat süreçlerini Logo ve Excel ile yürütüyorum; e-Defter ve e-Fatura uygulamalarına hâkimim.",
 pairs=[("Fatura kaydı yaptım.","Aylık 400'ü aşkın fatura kaydını Logo'da işledim; mutabakat farklarını iki iş gününe indirdim."),("Beyanname hazırladım.","KDV ve muhtasar beyannameleri süresinde hazırladım; ceza doğuran gecikme yaşanmadı.")],
 skills=[("Yazılım","Logo, Mikro, Luca, Zirve, SAP, Excel (pivot tablo, DÜŞEYARA/ÇAPRAZARA)"),("Mevzuat","VUK, KDV, gelir ve kurumlar vergisi, SGK, e-Dönüşüm"),("Süreç","Aylık kapanış, mutabakat, bilanço ve mizan analizi, bütçe raporlaması")],
 mist=["Programları listelemeden 'muhasebe bilgisi' yazmak","Rakamsız ve tarihsiz deneyim maddeleri","Eski mevzuat veya kullanılmayan yazılımları öne çıkarmak","İki sayfayı aşan, gereksiz detaylı bir CV","Yeni mezunken stajı ve sertifikaları yazmayı unutmak"],
 faq=[("Muhasebe elemanı CV'sinde hangi bölümler olmalı?","İletişim, kısa özet, deneyim, eğitim, kullandığınız programlar ve sertifikalar. Deneyimsizseniz stajı ve dönem projelerini deneyim gibi yazın."),("Muhasebe stajyeri CV'si nasıl yazılır?","Okul, bölüm, staj yeri ve öğrendiğiniz araçları yazın. Detay için <a href=\"/yeni-mezun-cv-ornegi\">yeni mezun CV örneğine</a> bakın."),("Muhasebecinin CV'sinde maaş beklentisi yazılır mı?","Genellikle hayır; ilan özellikle istemedikçe mülakata bırakın.")]),
dict(slug='ogretmen-cv-ornegi',short='Öğretmen CV Örneği',desc='Özel okul ve kurs başvuruları için öğretmen CV rehberi',
 title="Öğretmen CV Örneği: Özel Okul ve Kurs Başvurusu İçin CV Nasıl Hazırlanır?",
 mdesc="Öğretmen CV örneği ve rehberi: özel okul, dershane ve kurumlara başvuran branş öğretmenleri için CV yazımı, sertifikalar ve başarı örnekleri.",
 kw='öğretmen cv örneği, özel okul öğretmen cv, öğretmen cv nasıl hazırlanır, branş öğretmeni cv, sınıf öğretmeni cv, dershane öğretmen cv',
 h1='Öğretmen CV Örneği: Özel Okul ve Kurs Başvurusu',
 lede="Kamu atamaları resmî sistemle yürür; özel okul, kurs ve dershane başvurularında ise CV ve kısa bir ön yazı belirleyicidir. Öğretmen CV'sinde amaç, sınıftaki etkinizi somut sonuçlarla göstermektir.",
 must=["Branşınız ve eğitim verdiğiniz sınıf düzeyi","Formasyon, yüksek lisans ve ilgili sertifikalar","Sınıf yönetimi ve ölçme değerlendirme deneyimi","Kullandığınız dijital araçlar ve eğitim teknolojileri","Proje, kulüp ve okul dışı etkinlik çalışmaları"],
 sample="6 yıllık deneyime sahip matematik öğretmeni. Ortaokul ve lise düzeyinde ders verdim; sınav hazırlık gruplarında ortalama başarıyı artıran çalışma programları hazırladım. Dijital ölçme araçlarını aktif kullanırım.",
 pairs=[("Matematik dersi verdim.","8. sınıf gruplarında haftalık deneme ve analiz sistemi kurarak sınav ortalamasını dönem içinde artırdım."),("Veli toplantılarına katıldım.","Dönemlik veli görüşmelerini planlayıp öğrenci gelişim raporlarıyla yürüttüm.")],
 skills=[("Öğretim","Ders planlama, ölçme değerlendirme, bireysel destek, sınav hazırlık"),("Teknoloji","Akıllı tahta, çevrimiçi ders araçları, EBA, ölçme platformları"),("Kişisel","Sınıf yönetimi, iletişim, veli ile çalışma, takım çalışması")],
 mist=["Yalnızca ders saatlerini yazıp sonuç belirtmemek","Branş ve sınıf düzeyini gizlemek","Sertifikaları önem sırasına koymamak","Uzun ve süslü bir kişisel felsefe paragrafı yazmak","Kişisel bilgilerle birlikte gereksiz özel hayat bilgisi vermek"],
 faq=[("Öğretmen CV'sine fotoğraf koyulur mu?","Okullarda yaygındır ama zorunlu değildir; düzgün ve sade bir fotoğraf tercih edin."),("Yeni mezun öğretmen CV'sinde ne yazılır?","Okul uygulaması, staj, gönüllü eğitim projeleri ve sertifikalar. <a href=\"/yeni-mezun-cv-ornegi\">Yeni mezun rehberi</a> aynı mantıkla yardımcı olur."),("Ön yazı gerekli mi?","Özel okul başvurularında kısa bir <a href=\"/on-yazi-nasil-yazilir\">ön yazı</a> fark yaratır.")]),
dict(slug='hemsire-cv-ornegi',short='Hemşire CV Örneği',desc='Hastane ve klinik başvuruları için hemşire CV rehberi',
 title="Hemşire CV Örneği: Hastane ve Klinik Başvurusu İçin CV Nasıl Hazırlanır?",
 mdesc="Hemşire CV örneği ve rehberi: yoğun bakım, acil, servis ve ameliyathane deneyimini anlatan, sertifikaları öne çıkaran ATS uyumlu hemşire CV'si.",
 kw='hemşire cv örneği, hemşire cv nasıl hazırlanır, hastane cv örneği, yoğun bakım hemşiresi cv, sağlık personeli cv, hemşire özgeçmiş',
 h1='Hemşire CV Örneği: Nasıl Hazırlanır?',
 lede="Hastane ve klinikler CV'de önce çalıştığınız birimi, hasta profilini ve sertifikalarınızı arar. Hemşire CV'sini bu bilgiler bir bakışta okunacak şekilde kısa ve net tutun.",
 must=["Çalıştığınız birim (servis, yoğun bakım, acil, ameliyathane) ve hasta/yatak kapasitesi","Sağlık kuruluşunun türü ve deneyim süresi","Temel Yaşam Desteği, İleri Kardiyak Yaşam Desteği gibi sertifikalar","Uyguladığınız protokoller ve hasta güvenliği çalışmaları","Vardiya düzenine uygunluk ve gerekirse yabancı dil"],
 sample="5 yıllık deneyime sahip yoğun bakım hemşiresi. 12 yataklı erişkin yoğun bakım ünitesinde ventilatörlü hasta bakımı ve ekip koordinasyonu yürüttüm; Temel Yaşam Desteği sertifikam bulunuyor.",
 pairs=[("Hasta bakımı yaptım.","12 yataklı yoğun bakımda vardiya başına 2-3 hastanın bakımını ve ilaç uygulamalarını yürüttüm."),("Ekip çalışması yaptım.","Yeni gelen hemşirelere birim oryantasyonu vererek uyum sürelerini kısalttım.")],
 skills=[("Klinik","Vital takip, ilaç uygulama, pansuman, invaziv işlem desteği"),("Sertifika","Temel Yaşam Desteği, İleri Kardiyak Yaşam Desteği, enfeksiyon kontrolü eğitimleri"),("Kişisel","Stres altında karar verme, hasta ve yakını iletişimi, vardiya uyumu")],
 mist=["Birim ve kurum türünü belirtmemek","Sertifikaların tarihlerini yazmamak","Hasta bilgilerini veya kimliklerini paylaşmak (asla yazmayın)","Yalnızca görev listesi yazıp etkiyi belirtmemek","Uzun ve düzensiz bir CV hazırlamak"],
 faq=[("Hemşire CV'sinde sertifikalar nereye yazılır?","Eğitim bölümünün hemen ardından ayrı bir sertifikalar başlığında, tarihiyle birlikte."),("Yeni mezun hemşire CV'sinde ne olmalı?","Klinik staj birimleri, aldığınız eğitimler ve gönüllü sağlık çalışmaları."),("Fotoğraf koyulmalı mı?","Sağlık sektöründe yaygın; sade ve güncel olması yeterli.")]),
dict(slug='muhendis-cv-ornegi',short='Mühendis CV Örneği',desc='Makine, inşaat, elektrik mühendisleri için CV rehberi',
 title="Mühendis CV Örneği: Makine, İnşaat ve Elektrik Mühendisi CV'si Nasıl Yazılır?",
 mdesc="Mühendis CV örneği ve rehberi: makine, inşaat, elektrik-elektronik ve endüstri mühendisleri için proje odaklı, ATS uyumlu CV yazımı ve örnek cümleler.",
 kw='mühendis cv örneği, makine mühendisi cv, inşaat mühendisi cv, elektrik mühendisi cv, endüstri mühendisi cv, mühendis cv nasıl hazırlanır, saha mühendisi cv',
 h1='Mühendis CV Örneği: Proje ve Sonuç Odaklı Yazım',
 lede="Mühendis CV'sinde işveren şunu görmek ister: hangi projede, hangi araçlarla, ne büyüklükte bir sorumluluk aldınız ve sonuç ne oldu? Bölümünüz ne olursa olsun bu yapı ortaktır.",
 must=["Bölüm, okul ve mezuniyet yılı; varsa ilgili oda üyeliği","Proje adı, büyüklüğü, rolünüz ve süresi","Kullandığınız yazılımlar (AutoCAD, SolidWorks, ANSYS, MATLAB, Primavera vb.)","Kalite, iş güvenliği (İSG) ve standart bilginiz","Saha, ofis veya vardiya çalışma esnekliğiniz"],
 sample="Makine mühendisi; 5 yıl imalat sektöründe üretim ve proses iyileştirme deneyimi. SolidWorks ve AutoCAD ile tasarım, ISO 9001 sistemlerinde kalite süreçleri; saha çalışmasına uygunum.",
 pairs=[("Üretim hattında çalıştım.","Montaj hattı dengelemesi yaparak çevrim süresini kısalttım ve günlük üretimi artırdım."),("Proje yönettim.","12 kişilik şantiye ekibiyle 6 aylık bir betonarme projeyi zamanında teslim ettim.")],
 skills=[("Yazılım","AutoCAD, SolidWorks, ANSYS, MATLAB, Primavera, MS Project"),("Teknik","Proje yönetimi, kalite kontrol, proses iyileştirme, iş güvenliği"),("Kişisel","Saha yönetimi, raporlama, ekip koordinasyonu, tedarikçi iletişimi")],
 mist=["Yalnızca ünvan ve şirket yazıp proje bilgisi vermemek","Bildiği her programı listelemek","Rakam ve sonuç belirtmemek","Çok sütunlu, ikonlu ve tarama sistemlerinde bozulan şablonlar","Staj ve bitirme projesini yeni mezunken yazmamak"],
 faq=[("Mühendis CV'si kaç sayfa olmalı?","Beş yıla kadar tek sayfa; daha uzun deneyimde iki sayfa."),("Yeni mezun mühendis CV'sinde ne öne çıkarılır?","Staj, bitirme projesi, yarışma ve topluluk çalışmaları ile kullanılan yazılımlar."),("Saha mühendisi ile ofis mühendisi CV'si farklı mı?","Evet; saha rollerinde şantiye büyüklüğü, ekip ve iş güvenliği, ofis rollerinde tasarım ve analiz öne çıkar.")]),
dict(slug='kasiyer-tezgahtar-cv-ornegi',short='Kasiyer CV Örneği',desc='Market, mağaza ve perakende için kasiyer ve tezgâhtar CV rehberi',
 title="Kasiyer CV Örneği: Market, Mağaza ve Perakende İçin CV Nasıl Hazırlanır?",
 mdesc="Kasiyer ve tezgâhtar CV örneği: market, mağaza ve perakende ilanları için deneyimli ya da deneyimsiz adaylara kısa, net ve etkili CV hazırlama rehberi.",
 kw='kasiyer cv örneği, market kasiyeri cv, tezgahtar cv örneği, satış danışmanı cv, mağaza çalışanı cv, perakende cv, kasiyer cv nasıl hazırlanır',
 h1='Kasiyer ve Tezgâhtar CV Örneği',
 lede="Perakende ilanlarında CV'nin görevi kısa sürede güven vermektir: hızlı ve hatasız kasa kullanımı, müşteriyle iletişim, vardiya uyumu ve devamlılık. Tek sayfalık sade bir CV bunun için yeterlidir.",
 must=["Kasa ve POS cihazı kullanma deneyimi","Müşteri karşılama ve sorun çözme","Raf düzeni, stok sayımı ve ürün yerleştirme","Vardiyalı ve hafta sonu çalışma uygunluğu","Ehliyet ve varsa kısa mesleki kurs belgesi"],
 sample="3 yıllık market deneyimine sahip kasiyer. Yoğun saatlerde hızlı ve hatasız kasa kullanımı, müşteri memnuniyeti ve raf düzeni konularında deneyimliyim; vardiyalı çalışmaya uygunum.",
 pairs=[("Kasada çalıştım.","Günlük ortalama 300 müşteriye hizmet verdim; kasa farkı olmadan gün sonu kapanışı yaptım."),("Reyon düzenledim.","Haftalık stok sayımı ve raf düzenini yürüterek fire kayıplarını azalttım.")],
 skills=[("Kasa","POS ve kasa programı, nakit ve kart işlemleri, iade işlemleri"),("Müşteri","İletişim, şikâyet yönetimi, ürün yönlendirme"),("Depo ve raf","Stok sayımı, raf düzeni, etiketleme")],
 mist=["CV'yi çok uzun ve süslü hazırlamak","İletişim bilgilerini yanlış yazmak","Vardiya uygunluğunu belirtmemek","Deneyimsizken hiçbir bilgi yazmamak (eğitim, gönüllülük, kurs yazın)","Yazım hataları"],
 faq=[("Deneyimsiz kasiyer CV'sinde ne yazılır?","Eğitim, dil, bilgisayar ve müşteriyle çalıştığınız her türlü gönüllü veya part-time çalışmayı yazın."),("Kasiyer için ön yazı gerekli mi?","Zorunlu değil; kısa iki cümlelik bir e-posta metni faydalı olur."),("Fotoğraf koymalı mıyım?","Perakendede yaygındır; düzgün ve gülümseyen bir fotoğraf tercih edilebilir.")]),
]

# Evergreen makaleler ayrı dict
MULAKAT=[("Kendinizden bahseder misiniz?","Doğum yerinizle başlamayın. Şu anki rolünüz, deneyiminiz ve bu işe uygun iki güçlü yönünüzü 60-90 saniyede anlatın."),
("Neden bu pozisyona başvurdunuz?","İlanı ve şirketi okuduğunuzu gösterin; ne katacağınızı ve ne öğreneceğinizi net söyleyin."),
("Güçlü ve zayıf yönleriniz neler?","Güçlü yönü somut bir örnekle destekleyin. Zayıf yön olarak gerçek ama düzeltmeye çalıştığınız bir alanı söyleyin."),
("Neden ayrıldınız (ayrılmak istiyorsunuz)?","Önceki işvereni kötülemeyin. Gelişim, yeni sorumluluk ve uygun bir fırsat vurgusu yapın."),
("Bir başarı örneği anlatır mısınız?","Durum, sizin yaptığınız, sonuç. Rakamla desteklenen kısa bir hikâye anlatın."),
("Zor bir durumla nasıl başa çıktınız?","Sorunu, aldığınız aksiyonu ve öğrendiğiniz dersi anlatın; suçlayıcı olmayın."),
("Maaş beklentiniz nedir?","Piyasa araştırması yapıp makul bir aralık verin; tek rakama kilitlenmeyin."),
("5 yıl sonra kendinizi nerede görüyorsunuz?","Hedefinizi bu işle ve şirketle uyumlu bir gelişim çizgisi olarak anlatın."),
("Sizi neden işe almalıyız?","İlandaki üç ana gereksinimi kendi deneyiminizle eşleştirin."),
("Bize soracağınız bir şey var mı?","Mutlaka soru sorun: ekip yapısı, ilk üç ay beklentisi ve başarı ölçütü gibi.")]
