import { paidAmountOk, PLANS, signAccess, verifyAccess } from '../netlify/functions/_lib.mjs';
import { sanitizeImported } from '../netlify/functions/_import.mjs';
let f = 0; const ok = (n, c) => { console.log(`${c ? 'PASS' : 'FAIL'}  ${n}`); if (!c) f++; };
const P = (o) => new URLSearchParams(o);
const order = { plan: 'pro', amount: 14900 };
ok('PayTR: tam tutar kabul', paidAmountOk(order, P({ total_amount: '14900' })));
ok('PayTR: taksit farkıyla fazla tutar kabul', paidAmountOk(order, P({ total_amount: '15600', payment_amount: '14900' })));
ok('PayTR: eksik tutar RED', !paidAmountOk(order, P({ total_amount: '100' })));
ok('PayTR: payment_amount eksikse RED', !paidAmountOk(order, P({ total_amount: '20000', payment_amount: '5900' })));
ok('PayTR: eski sipariş (amount yok) plan fiyatı ile', paidAmountOk({ plan: 'week' }, P({ total_amount: String(PLANS.week.amountTL * 100) })));
ok('PayTR: bilinmeyen plan RED', !paidAmountOk({ plan: 'xx' }, P({ total_amount: '999999' })));
ok('PayTR: boş tutar RED', !paidAmountOk(order, P({})));
process.env.TOKEN_SECRET = 'test-secret-1234567890';
const t = signAccess('CV1abc', 'pro', Date.now() + 1e6);
ok('Token imzala/doğrula', verifyAccess(t)?.plan === 'pro');
ok('Değiştirilmiş token RED', verifyAccess(t.replace('.pro.', '.proplus.')) === null);
const s = sanitizeImported({ personal: { fullName: 'A'.repeat(500), drivingLicense: ['b', 'src', 'XYZ'], maritalStatus: 'Dul' }, experiences: [{ company: 'X', achievements: ['a', 1, null] }, { }], skills: ['Excel', 'Excel', { name: 'SQL' }], languages: [{ name: 'Almanca', level: 'çok iyi' }], educations: [{ school: 'Y', degree: 'Master' }] });
ok('Sanitize: uzunluk sınırı', s.personal.fullName.length === 80);
ok('Sanitize: ehliyet', JSON.stringify(s.personal.drivingLicense) === '["B","SRC"]');
ok('Sanitize: geçersiz medeni durum boş', s.personal.maritalStatus === '');
ok('Sanitize: boş deneyim atılır', s.experiences.length === 1);
ok('Sanitize: yetenek tekil + nesne', s.skills.map((x) => x.name).join(',') === 'Excel,SQL');
ok('Sanitize: bilinmeyen seviye → B1', s.languages[0].level === 'B1');
ok('Sanitize: bilinmeyen derece → Lisans', s.educations[0].degree === 'Lisans');
ok('Sanitize: çöp girdi', sanitizeImported(null).experiences.length === 0 && sanitizeImported('x').personal.fullName === '');
console.log(f ? `${f} başarısız` : 'Birim testleri geçti'); process.exit(f ? 1 : 0);
